### ISSUE TITLE
Angular 4.2.4 - can't initiate

### ISSUE THREAD

**Issue by HollandRisley** [flehoux/angular-resizable-flex#5]
Hi, I am trying to use this module on Angular 4.2.4. I install a fresh Angular project from the Angular CLI, then follow the exact basic instructions here: https://bertrandg.github.io/angular-split/#/

This is the Error I receive: 

ERROR in Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule in /Users/hollandrisley/node_modules/@angular/core/core.d.ts, resolving symbol AngularSplitModule in /Users/hollandrisley/node_modules/angular-split/dist/angularSplit.module.d.ts, resolving symbol AngularSplitModule in /Users/hollandrisley/node_modules/angular-split/dist/angularSplit.module.d.ts
    at positionalError (/Users/hollandrisley/SourceCode/Test Project/SplitTesterApp/node_modules/@angular/compiler/bundles/compiler.umd.js:25134:35)
    at simplifyInContext (/Users/hollandrisley/SourceCode/Test Project/SplitTesterApp/node_modules/@angular/compiler/bundles/compiler.umd.js:24977:27)
    at StaticReflector.simplify (/Users/hollandrisley/SourceCode/Test Project/SplitTesterApp/node_modules/@angular/compiler/bundles/compiler.umd.js:24991:13)
    at StaticReflector.annotations (/Users/hollandrisley/SourceCode/Test Project/SplitTesterApp/node_modules/@angular/compiler/bundles/compiler.umd.js:24418:41)
    at _getNgModuleMetadata (/Users/hollandrisley/SourceCode/Test Project/SplitTesterApp/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (/Users/hollandrisley/SourceCode/Test Project/SplitTesterApp/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at /Users/hollandrisley/SourceCode/Test Project/SplitTesterApp/node_modules/@angular/compiler-cli/src/ngtools_impl.js:129:27
    at Array.reduce (native)
    at _extractLazyRoutesFromStaticModule (/Users/hollandrisley/SourceCode/Test Project/SplitTesterApp/node_modules/@angular/compiler-cli/src/ngtools_impl.js:128:10)
    at Object.listLazyRoutesOfModule (/Users/hollandrisley/SourceCode/Test Project/SplitTesterApp/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/Users/hollandrisley/SourceCode/Test Project/SplitTesterApp/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/Users/hollandrisley/SourceCode/Test Project/SplitTesterApp/node_modules/@ngtools/webpack/src/plugin.js:212:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (/Users/hollandrisley/SourceCode/Test Project/SplitTesterApp/node_modules/@ngtools/webpack/src/plugin.js:448:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)

This is my package.json:

`{
  "name": "split-tester-app",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.2.4",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "core-js": "^2.4.1",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.4.9",
    "@angular/compiler-cli": "^4.2.4",
    "@angular/language-service": "^4.2.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.2.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.3.3"
  }
}
`

**Comment by flehoux** [comment]
Hello @HollandRisley, 

The library is currently only written for angular 1, I could try and port things over.

PS: You linked another library in the issue :)
